config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'loans#index'

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update, :destroy]
  end

  resources :users, only: [:index, :show]

  get 'loans/index'

  resources :loans, only: [:new, :index, :create, :show] do
    member do
      patch :approve
      put :open
      put :close
      patch :reject
      patch :accept
      patch :repay
      get :set_interest_rate
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/loan.rb
class Loan < ApplicationRecord
  belongs_to :user
  belongs_to :admin, class_name: 'User', foreign_key: 'admin_id'

  validates :amount, presence: true, numericality: { greater_than: 0 }
  validates :state, presence: true, inclusion: { in: %w[requested approved open closed rejected] }
  validates :interest_rate, presence: true, numericality: { greater_than_or_equal_to: 0 }

  after_initialize :set_initial_values
  before_create :set_default_repay_amount

  scope :open, -> { where(state: 'open') }

  def formatted_interest_rate
    (interest_rate * 100).round(2)
  end

  def interest_rate_from_percentage(percentage)
    self.interest_rate = percentage.to_f / 100
  end

  def requested?
    state == 'requested'
  end

  def approve?
    state == 'approved'
  end

  def open?
    state == 'open'
  end

  def close!
    update(state: 'closed')
  end

  def reject!
    update(state: 'rejected')
  end

  def set_default_repay_amount
    self.repay_amount = self.amount
  end

  def open!
    Loan.transaction do
      admin = User.find_by(role: 'admin')
      raise 'Admin not found' unless admin

      admin_wallet = admin.wallet
      user_wallet = user.wallet

      if admin_wallet.amount >= amount
        admin_wallet.debit(amount)
        user_wallet.credit(amount)
        update!(state: 'open')
      else
        raise 'Insufficient funds in admin wallet'
      end
    end
  end

  def repay!
    Loan.transaction do
      total_to_repay = total_repay_amount
      user_wallet = user.wallet
      admin_wallet = admin.wallet

      if user_wallet.amount >= total_to_repay
        perform_full_repayment(user_wallet, admin_wallet, total_to_repay)
      else
        perform_partial_repayment(user_wallet, admin_wallet)
      end 
    end
  end

  def total_repay_amount
    open? ? self.repay_amount : 0
  end

  private

  def set_initial_values
    self.state ||= 'requested'
    self.interest_rate ||= 0.05
  end

  def perform_full_repayment(user_wallet, admin_wallet, total_to_repay)
    user_wallet.decrement!(:amount, total_to_repay)
    admin_wallet.increment!(:amount, total_to_repay)
    update(state: 'closed')
  end

  def perform_partial_repayment(user_wallet, admin_wallet)
    partial_amount = user_wallet.amount
    user_wallet.decrement!(:amount, partial_amount)
    admin_wallet.increment!(:amount, partial_amount)
    update(state: 'closed')
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :wallet, dependent: :destroy
  has_many :loans, dependent: :destroy

  after_create :create_default_wallet

  enum role: { user: 0, admin: 1 }

  scope :admins, -> { where(role: :admin) }

  def debit(amount)
    wallet.debit(amount)
  end

  def credit(amount)
    wallet.credit(amount)
  end

  def user?
    role == 'user'
  end

  private

  def create_default_wallet
    initial_amount = self.admin? ? 1000000 : 10000
    Wallet.create(user: self, amount: initial_amount, role: self.admin? ? 'admin' : 'user')
  end
end

app/models/wallet.rb
class Wallet < ApplicationRecord
  belongs_to :user

  def debit(amount)
    self.amount -= amount
    save!
  end

  def credit(amount)
    self.amount += amount
    save!
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_admin

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path(@user), notice: 'User updated successfully'
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path, notice: 'User deleted successfully'
  end

  private

  def user_params
    params.require(:user).permit(:email, :role)
  end

  def ensure_admin
    redirect_to root_path, alert: 'Access denied!' unless current_user.admin?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_wallet
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def set_wallet
    @wallet = current_user.wallet if user_signed_in?
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :set_loan, only: [:show, :approve, :reject, :accept, :close, :set_interest_rate]
  before_action :authenticate_user!

  def index
    @loans = current_user.admin? ? Loan.all : current_user.loans
    @wallet = current_user.wallet
  end

  def new
    @loan = Loan.new
  end

  def create
    @loan = current_user.loans.new(loan_params)
    @loan.admin = User.find_by(role: 'admin')

    if @loan.save
      render :show, status: :created, location: @loan
    else
      render json: @loan.errors, status: :unprocessable_entity
    end
  end

  def show
  end

  def approve
    interest_rate_percentage = params[:loan][:interest_rate].to_f
    interest  = @loan.interest_rate_from_percentage(interest_rate_percentage)
    @loan.update(state: 'approved', admin: current_user, interest_rate: interest)
    redirect_to loan_path(@loan), notice: 'Loan approved successfully.'
  end

  def repay
    @loan = Loan.find(params[:id])
    @loan.repay!

    redirect_to @loan, notice: 'Loan successfully repaid.'
  rescue StandardError => e
    flash[:alert] = "Error repaying loan: #{e.message}"
    redirect_back(fallback_location: root_path)
  end

  def reject
    @loan.reject!
    redirect_to @loan, notice: 'Loan was successfully rejected.'
  end

  def accept
    @loan.open!
    redirect_to @loan, notice: 'Loan was successfully accepted and is now open.'
  end

  def set_interest_rate
    render 'set_interest_rate'
  end

  def close
    @loan.close!
    redirect_to @loan, notice: 'Loan was successfully closed.'
  end

  private

  def set_loan
    @loan = Loan.find(params[:id])
  end

  def loan_params
    params.require(:loan).permit(:amount)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/loans_helper.rb
# app/helpers/loans_helper.rb
module LoansHelper
  def render_loan_actions_for_requested(loan)
    if current_user.admin?
      link_to('Approve', set_interest_rate_loan_path(loan), class: 'btn btn-primary btn-sm mr-2') +
      link_to('Reject', reject_loan_path(loan), data: { turbo_method: :patch }, class: 'btn btn-danger btn-sm ml-2')
    elsif current_user.user?
      link_to('Reject', reject_loan_path(loan), data: { turbo_method: :patch }, class: 'btn btn-danger btn-sm')
    end
  end

  def render_loan_actions_for_approved(loan)
    if current_user.admin?
      link_to('Reject', reject_loan_path(loan), data: { turbo_method: :patch }, class: 'btn btn-danger btn-sm')
    else
      link_to('Accept', accept_loan_path(loan), data: { turbo_method: :patch }, class: 'btn btn-success btn-sm mr-2') +
      link_to('Reject', reject_loan_path(loan), data: { turbo_method: :patch }, class: 'btn btn-danger btn-sm ml-2')
    end
  end

  def render_loan_actions_for_open(loan)
    link_to('Repay', repay_loan_path(loan), data: { turbo_method: :patch }, class: 'btn btn-info btn-sm') if current_user.user?
  end
end

app/views/admin/users/destroy.html.erb
<h1>Admin::Users#destroy</h1>
<p>Find me in app/views/admin/users/destroy.html.erb</p>

app/views/admin/users/edit.html.erb
<h1>Admin::Users#edit</h1>
<p>Find me in app/views/admin/users/edit.html.erb</p>

app/views/admin/users/index.html.erb
<h1>Admin::Users#index</h1>
<p>Find me in app/views/admin/users/index.html.erb</p>

app/views/admin/users/show.html.erb
<h1>Admin::Users#show</h1>
<p>Find me in app/views/admin/users/show.html.erb</p>

app/views/admin/users/update.html.erb
<h1>Admin::Users#update</h1>
<p>Find me in app/views/admin/users/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LendMoneyApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

    <%= stylesheet_link_tag "application", media: 'all', "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= alert %>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <% if user_signed_in? %>
        <div class="container-fluid d-flex justify-content-between align-items-center">
          <div>
            <h5>Welcome, <%= current_user.username %></h5>
          </div>
          
          <div class="d-flex align-items-center">
            <p class="mb-0 mr-3">Your wallet amount: <b><%= number_to_currency(@wallet.amount, unit: '₹') %></b></p>
            <%= link_to t('navigation.log_out'), destroy_user_session_path, class: 'btn btn-outline-danger btn-sm', data: { turbo_method: :delete }, style: 'margin-left: 10px;' %>
          </div>
        </div>
      <% end %>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/loans/approve.html.erb
<h1>Approve Loan</h1>

<%= form_with(model: @loan, url: approve_loan_path(@loan), method: :patch) do |form| %>
  <div class="field">
    <%= form.label :interest_rate %>
    <%= form.number_field :interest_rate, step: 0.01, value: @loan.interest_rate || 5 %>
  </div>

  <div class="actions">
    <%= form.submit 'Approve Loan' %>
  </div>
<% end %>

<%= link_to 'Back', loans_path %>

app/views/loans/index.html.erb
<div class="mt-4 text-center">
  <h5>All Loans</h5>

  <% if current_user.user? %>
    <%= link_to 'Request a Loan', new_loan_path, class: 'btn btn-primary btn-sm' %>
  <% end %>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>User</th>
        <th>Email ID</th>
        <th>Amount</th>
        <th>Interest(%)</th>
        <% if current_user.user? %>
          <th>Repaid Amount</th>
        <% end %>
        <th>Status</th>
        <% if @loans.any? { |loan| loan.state != 'rejected' } %>
          <th>Actions</th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% active_loans = @loans.select { |loan| loan.state != 'closed' && loan.state != 'rejected' } %>
      <% inactive_loans = @loans.select { |loan| loan.state == 'closed' || loan.state == 'rejected' } %>

      <% active_loans.each do |loan| %>
        <tr>
          <td><%= loan.user.username %></td>
          <td><%= loan.user.email %></td>
          <td><%= number_to_currency(loan.amount, unit: '₹') %></td>
          <td><%= number_with_precision(loan.interest_rate * 100, precision: 2) %></td>
          <% if current_user.user? %>
            <td><%= number_to_currency(loan.total_repay_amount, unit: '₹') %></td>
          <% end %>
          <td><%= loan.state.capitalize %></td>
          <td>
            <% case loan.state %>
            <% when 'requested' %>
              <%= render_loan_actions_for_requested(loan) %>
            <% when 'approved' %>
              <%= render_loan_actions_for_approved(loan) %>
            <% when 'open' %>
              <%= render_loan_actions_for_open(loan) %>
            <% end %>
          </td>
        </tr>
      <% end %>

      <% inactive_loans.each do |loan| %>
        <tr>
          <td><%= loan.user.username %></td>
          <td><%= loan.user.email %></td>
          <td><%= number_to_currency(loan.amount, unit: '₹') %></td>
          <td><%= number_with_precision(loan.interest_rate * 100, precision: 2) %></td>
          <% if current_user.user? %>
            <td><%= number_to_currency(loan.total_repay_amount, unit: '₹') %></td>
          <% end %>
          <td><%= loan.state.capitalize %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/loans/new.html.erb
<div class="container d-flex justify-content-center align-items-center" style="height: 100vh;">
  <div class="card p-4" style="width: 400px;">
  <h5 class="text-center">New Loan</h5>

<%= form_with(model: @loan, url: loans_path, class: 'form') do |form| %>
  <% if @loan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@loan.errors.count, "error") %> prohibited this loan from being saved:</h2>

      <ul>
        <% @loan.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :amount, class: 'control-label' %>
    <%= form.number_field :amount, class: 'form-control' %>
  </div>

  <div class="form-group text-center">
    <%= form.submit 'Create Loan', class: 'btn btn-primary btn-sm mt-3' %>
  </div>
<% end %>
  </div>
</div>

app/views/loans/set_interest_rate.html.erb
<div class="container mt-5">
  <div class="card p-4" style="max-width: 400px; margin: 0 auto;">
    <h5 class="text-center">Set Interest Rate for Loan</h5>

    <%= form_with(model: @loan, url: approve_loan_path(@loan), data: { turbo_method: :put }) do |form| %>
      <div class="form-group">
        <%= form.label :interest_rate %>
        <%= form.text_field :interest_rate, value: number_with_precision(@loan.interest_rate * 100, precision: 2), class: 'form-control' %>
      </div>

      <div class="form-group text-center mt-3">
        <%= form.submit 'Set Interest Rate', class: 'btn btn-primary btn-sm' %>
        <%= link_to 'Back', loan_path(@loan), class: 'btn btn-primary btn-sm ml-2' %>
      </div>
    <% end %>
  </div>
</div>

app/views/loans/show.html.erb
<div class="container mt-5">
  <h5 class="text-center">Loan Details</h5>

  <table class="table table-striped">
    <tbody>
      <tr>
        <th>User:</th>
        <td><%= @loan.user.username%></td>
      </tr>
      <tr>
        <th>User Email ID:</th>
        <td><%= @loan.user.email%></td>
      </tr>
      <tr>
        <th>Admin:</th>
        <td><%= @loan.admin.username %></td>
      </tr>
      <tr>
        <th>Amount:</th>
        <td><%= number_to_currency(@loan.amount, unit: '₹') %></td>
      </tr>
      <tr>
        <th>Interest Rate:</th>
        <td><%= number_with_precision(@loan.interest_rate * 100, precision: 2) %>%</td>
      </tr>
      <tr>
        <th>Total Amount to be Repaid:</th>
        <td><%= number_to_currency(@loan.total_repay_amount, unit: '₹') %></td>
      </tr>
      <tr>
        <th>Status:</th>
        <td><%= @loan.state.capitalize %></td>
      </tr>
      <tr>
        <th>Created At:</th>
        <td><%= @loan.created_at.strftime("%B %d, %Y %H:%M") %></td>
      </tr>
    </tbody>
  </table>

  <div class="text-center">
    <%= link_to 'Back to Loans', loans_path, class: 'btn btn-primary btn-sm' %>
  </div>
</div>